### ISSUE TITLE
The same "fix: allow use zeegaree without unity" needs to be done for Zeegaree-Lite also

### ISSUE THREAD

**Issue by scott092707** [mivoligo/Zeegaree-Lite#2]
I just installed Lubuntu Next 17.10, and whether it is because I am now using Lubuntu Next, or because I went from 17.04 to 17.10, Zeegaree-Lite would not run* until I found the fix for Zeegaree, and made most of the alterations shown on: "https://github.com/mivoligo/Zeegaree/commit/f9cff56b13d223441d23d4a3290dcfc1ca1f0cd4"
(The code referencing "Pomodoro" was not applicable for Zeegaree-Lite)
The line:
LAUNCHER = Unity.LauncherEntry.get_for_desktop_id("zeegaree.desktop")
needed to be altered to:
LAUNCHER = Unity.LauncherEntry.get_for_desktop_id("zeegaree-lite.desktop")
as well)
-----------------------------------------------------------------------------
*Terminal output showing bug:
-----------------------------------------------------------------------------
scott@scott-Asus-M2N68-AM-PLUS:~$  python /data/scott/Downloads/Zeegaree-Lite-master/zeegaree_lite.py
/data/scott/Downloads/Zeegaree-Lite-master/zeegaree_lite.py:21: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Unity, Notify
Traceback (most recent call last):
  File "/data/scott/Downloads/Zeegaree-Lite-master/zeegaree_lite.py", line 21, in <module>
    from gi.repository import Unity, Notify
ImportError: cannot import name Unity
-------------------------------------------------------------------------------
(by the way:
I don't know what to do about the PyGIWarning, as when I add the line "gi.require_version('Notify', '0.7')" before "from gi.repository import Notify"
I get:
scott@scott-Asus-M2N68-AM-PLUS:~$ python /data/scott/Downloads/Zeegaree-Lite-master/zeegaree_lite.py
Traceback (most recent call last):
  File "/data/scott/Downloads/Zeegaree-Lite-master/zeegaree_lite.py", line 22, in <module>
    gi.require_version('Notify', '0.7')
NameError: name 'gi' is not defined
)
=================================================================
scott@scott-Asus-M2N68-AM-PLUS:~$ uname -a
Linux scott-Asus-M2N68-AM-PLUS 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
scott@scott-Asus-M2N68-AM-PLUS:~$ lsb_release -dsc
Ubuntu 17.10
artful
scott@scott-Asus-M2N68-AM-PLUS:~$ echo $DESKTOP_SESSION
QLubuntu

Zeegaree-Lite 1.2

**Comment by mathieu2em** [comment]
same than higher

**Comment by mivoligo** [comment]
Sorry but I'm not maintaining this project any more.
